version: '3.5'

services:

    backend:
        image: back
        restart: unless-stopped
        ports:
          - 8000:8000
        environment:
          - FRONT_URL=frontend:5000
          - REDIS=redis
          - REDIS_PORT=6379
          - DB_USERNAME=postgres
          - DB_PASSWORD=example
          - DB_HOST=db
        depends_on:
          - redis
          - db

    frontend:
        image: front
        restart: unless-stopped
        ports:
          - 5000:5000
        environment:
          - API_URL=backend:8000

    redis:
        image: redis
        ports:
          - 6379:6379

    db:
        image: postgres
        restart: unless-stopped
        environment:
          POSTGRES_PASSWORD: example
        volumes:
          - database:/var/lib/postgresql/data

volumes:
  database:
